### ISSUE TITLE
Lägg till länk till kundo här för att komma igång

### ISSUE THREAD

**Issue by karleklof** [kundo/kundo-sitevision#4]
https://github.com/kundo/kundo-sitevision/blob/f8b784581d8885891d2b02252fa4237681495c36/kundo-chat/src/config/index.html#L13

Om kunden inte har konto hos er så skulle det nog vara bra att lägga till en länk här så att de kan kontakta er typ så här:
```
<p class="help-block">Bla bla... <a href="...">klick här</a></p>
```

**Comment by EmilStenstrom** [comment]
Tack, det är en jättebra idé! Stängd via https://github.com/kundo/kundo-sitevision/commit/11ed0b3f028f250bdf58dcf788539ea2f0c05b53
