### ISSUE TITLE
Lägg till Marketplace information

### ISSUE THREAD

**Issue by karleklof** [kundo/kundo-sitevision#5]
Skapa en mapp "marketplace" i rooten som innehåller alla screenshots, logga och en readme.md.
Readme.md ska innehålla informationen som ska synas i på sidan i Marketplace

**Comment by EmilStenstrom** [comment]
Uppfattat! Fixat i https://github.com/kundo/kundo-sitevision/commit/3223d48e9daf9f6ae6558255fea3ae9e211e2629
